FROM huggingface/transformers-pytorch-gpu:latest
COPY . /ws
WORKDIR /ws
RUN conda env create -f environment.yml
ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8080"]